/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket_reservation.views.screen;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ticket_reservation.models.user;
import ticket_reservation.views.screen.dashboard_screen;

public class ticket_screen extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    PreparedStatement pst2;
    private final String url = "jdbc:mysql://localhost:3306/tiket_reservation?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private final String username = "root";
    private final String pass = "";
    int id_user;
   

    public ticket_screen(int id_user) {
        initComponents();
        this.id_user = id_user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        select = new javax.swing.JButton();
        show = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Refund = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        titleRs = new javax.swing.JLabel();
        genreRs = new javax.swing.JLabel();
        ratingRs = new javax.swing.JLabel();
        dateRs = new javax.swing.JLabel();
        timeRs = new javax.swing.JLabel();
        studioRs = new javax.swing.JLabel();
        seatRs = new javax.swing.JLabel();
        priceRs = new javax.swing.JLabel();
        totalRs = new javax.swing.JLabel();
        qtyRs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Movie Title", "Genres", "Ratings"
            }
        ));
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(20);
            table.getColumnModel().getColumn(1).setPreferredWidth(250);
            table.getColumnModel().getColumn(2).setPreferredWidth(140);
            table.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        select.setBackground(new java.awt.Color(0, 0, 0));
        select.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        select.setForeground(new java.awt.Color(255, 255, 255));
        select.setText("Select Ticket");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        show.setBackground(new java.awt.Color(0, 0, 153));
        show.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("Show Tickets");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(select)
                    .addComponent(backButton))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(show)
                .addGap(257, 257, 257))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)
                        .addGap(64, 64, 64)
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Ticket Details");

        jLabel4.setText("Title: ");

        jLabel5.setText("Genre: ");

        jLabel6.setText("Ratings: ");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Date & Showtime");

        jLabel8.setText("Date:");

        jLabel9.setText("Time: ");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Seat & Qty");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Total");

        jLabel12.setText("Studio: ");

        jLabel13.setText("Seat: ");

        jLabel14.setText("Qty:");

        jLabel15.setText("Price: ");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Total:");

        Refund.setBackground(new java.awt.Color(255, 51, 51));
        Refund.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refund.setForeground(new java.awt.Color(255, 255, 255));
        Refund.setText("Refund");
        Refund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefundActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(51, 102, 255));
        edit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genreRs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ratingRs, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titleRs, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(timeRs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateRs, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(totalRs, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(studioRs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qtyRs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(priceRs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(seatRs, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Refund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(titleRs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(genreRs)
                            .addComponent(studioRs)
                            .addComponent(qtyRs))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(ratingRs)
                            .addComponent(seatRs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(dateRs)
                            .addComponent(priceRs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel16)
                            .addComponent(timeRs)
                            .addComponent(totalRs)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Refund, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        try {
            String studioName = null, date = null, time = null, seat = null, title = null, genre = null, rating = null;
            int qty = 0, total = 0, price = 0;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, username, pass);

            int row = table.getSelectedRow();
            DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
            String id = (String) tblModel.getValueAt(row, 0);
            String query = "SELECT b.nama, t.jumlah_tiket, t.tanggal, t.waktu, t.total_harga FROM tiket_order AS t JOIN bioskop AS b ON b.id = t.id_bioskop WHERE `id_user` = '" + id_user + "'" + "AND `id_order` = '" + id + "'";
            pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                studioName = rs.getString("nama");
                qty = rs.getInt("jumlah_tiket");
                date = rs.getString("tanggal");
                time = rs.getString("waktu");
                total = rs.getInt("total_harga");
            }

            price = total / qty;
            switch (price) {
                case 30000:
                    seat = "Reguler";
                    break;
                case 50000:
                    seat = "VIP";
                    break;
                case 100000:
                    seat = "Private VIP";
                    break;
                default:
                    break;
            }

            query = "SELECT f.judul, f.genre, f.ratings FROM tiket_order AS t JOIN film AS f ON f.id = t.id_film WHERE `id_user` = '" + id_user + "'" + "AND `id_order` = '" + id + "'";
            pst2 = con.prepareStatement(query);
            ResultSet rs2 = pst2.executeQuery();

            while (rs2.next()) {
                title = rs2.getString("judul");
                genre = rs2.getString("genre");
                rating = rs2.getString("ratings");
            }

            titleRs.setText(title);
            genreRs.setText(genre);
            ratingRs.setText(rating);
            dateRs.setText(date);
            timeRs.setText(time);
            studioRs.setText(studioName);
            qtyRs.setText(Integer.toString(qty));
            seatRs.setText(seat);
            priceRs.setText("Rp. " + Integer.toString(price) + ",00");
            totalRs.setText("Rp. " + Integer.toString(total) + ",00");

            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_selectActionPerformed

    private void RefundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefundActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, username, pass);

            int row = table.getSelectedRow();
            DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
            String id = (String) tblModel.getValueAt(row, 0);
            String query = "DELETE FROM tiket_order WHERE id_order = ? ";
            pst = con.prepareStatement(query);
            pst.setString(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Tiket Berhasil DiRefund!");

            tblModel.setRowCount(0);
            titleRs.setText("");
            genreRs.setText("");
            ratingRs.setText("");
            dateRs.setText("");
            timeRs.setText("");
            studioRs.setText("");
            qtyRs.setText("");
            seatRs.setText("");
            priceRs.setText("");
            totalRs.setText("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefundActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, username, pass);
            
            int row = table.getSelectedRow();
            DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
            String id = (String) tblModel.getValueAt(row, 0);
            
            edit_screen et = new edit_screen(id, id_user);
            et.setVisible(true);
            this.dispose();
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, username, pass);
            String query = "SELECT t.id_order, f.judul, f.genre, f.ratings, f.poster FROM tiket_order AS t JOIN film AS f ON f.id = t.id_film  WHERE `id_user` = '" + id_user + "'";
            pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id_order"));
                String title = rs.getString("judul");
                String genre = rs.getString("genre");
                String rating = rs.getString("ratings");
                String poster = rs.getString("poster");

                String movieData[] = {id, title, genre, rating};
                DefaultTableModel tblModel = (DefaultTableModel) table.getModel();

                tblModel.addRow(movieData);
            }

            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        backButtonAction();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refund;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dateRs;
    private javax.swing.JButton edit;
    private javax.swing.JLabel genreRs;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel priceRs;
    private javax.swing.JLabel qtyRs;
    private javax.swing.JLabel ratingRs;
    private javax.swing.JLabel seatRs;
    private javax.swing.JButton select;
    private javax.swing.JButton show;
    private javax.swing.JLabel studioRs;
    private javax.swing.JTable table;
    private javax.swing.JLabel timeRs;
    private javax.swing.JLabel titleRs;
    private javax.swing.JLabel totalRs;
    // End of variables declaration//GEN-END:variables

    private void backButtonAction() {
       new dashboard_screen(id_user).setVisible(true);
       this.dispose();
    }
}
